spring:
  application:
    name: server
  profiles:
    include: secret
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
front:
  domain: localhost:3000
  protocol: http
  url: "${front.protocol}://${front.domain}"
