spring:
  datasource:
    url: jdbc:mysql://localhost:3306/repostory
    username: {db id}
    password: {db pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: {sender email}
    password: {sender pwd}
  jwt:
    secret: {secretKey}